---    
        
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
    
    - name: restart ntp
      ansible.builtin.service:
        name: ntp
        state: restarted

    - name: restart ssh
      ansible.builtin.service:
        name: ssh
        state: restarted
